Repository 0-Crew/i-zero-s, pull requests merged in 2021-12, with the labels that each got.

#25 팔로우/보틀월드/상단탭바
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.swift
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.xib
  Code-Zero/Screen/BottleWorld/Cell/TopTabBarCell.swift
  Code-Zero/Screen/BottleWorld/Cell/TopTabBarCell.xib
  Code-Zero/Screen/BottleWorld/StoryBoard/BottleWorld.storyboard
  Code-Zero/Screen/BottleWorld/VC/BottleWorldVC.swift
  Code-Zero/Screen/BottleWorld/View/FollowEmptyView.xib
  Code-Zero/Screen/BottleWorld/View/SwipeBarView.swift
  Code-Zero/Support/Info.plist
Labels: 민희🍪, layout💄

#27 spm추가/Gedatsu
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Support/Delegate/AppDelegate.swift
  Code-Zero/Support/Info.plist
Labels: style, 민희🍪

#28 팔로우/보틀월드/결과없음
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.swift
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.xib
  Code-Zero/Screen/BottleWorld/VC/BottleWorldVC.swift
  Code-Zero/Screen/BottleWorld/View/FollowEmptyView.swift
  Code-Zero/Screen/BottleWorld/View/FollowEmptyView.xib
  Code-Zero/Support/Assets.xcassets/icSearch.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icSearch.imageset/icSearch.png
  Code-Zero/Support/Assets.xcassets/icSearch.imageset/icSearch@2x.png
  Code-Zero/Support/Assets.xcassets/icSearch.imageset/icSearch@3x.png
  Code-Zero/Support/Assets.xcassets/imgFollowNone.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/imgFollowNone.imageset/imgFollowNone.png
  Code-Zero/Support/Assets.xcassets/imgFollowNone.imageset/imgFollowNone@2x.png
  Code-Zero/Support/Assets.xcassets/imgFollowNone.imageset/imgFollowNone@3x.png
  Code-Zero/Support/Assets.xcassets/imgSearchNone.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/imgSearchNone.imageset/imgSearchNone.png
  Code-Zero/Support/Assets.xcassets/imgSearchNone.imageset/imgSearchNone@2x.png
  Code-Zero/Support/Assets.xcassets/imgSearchNone.imageset/imgSearchNone@3x.png
  Code-Zero/Support/Info.plist
Labels: 민희🍪, layout💄

#30 챌린지/오픈
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/View/LoadXibView.swift
  Code-Zero/Screen/Challenge/Cell/ChallengeListCell.swift
  Code-Zero/Screen/Challenge/Cell/OptionCell.swift
  Code-Zero/Screen/Challenge/VC/ChallengeVC.swift
  Code-Zero/Screen/ChallengeOpen/Model/ChallengeOpenStep.swift
  Code-Zero/Screen/ChallengeOpen/Storyboards/ChallengeOpen.storyboard
  Code-Zero/Screen/ChallengeOpen/Storyboards/ChallengeOpenFirstStepView.xib
  Code-Zero/Screen/ChallengeOpen/Storyboards/ChallengeOpenSecondStepView.xib
  Code-Zero/Screen/ChallengeOpen/Storyboards/ChallengeOpenThirdStepView.xib
  Code-Zero/Screen/ChallengeOpen/VC/ChallengeOpenVC.swift
  Code-Zero/Screen/ChallengeOpen/View/ChallengeOpenFirstStepView.swift
  Code-Zero/Screen/ChallengeOpen/View/ChallengeOpenSecondStepView.swift
  Code-Zero/Screen/ChallengeOpen/View/ChallengeOpenThirdStepView.swift
  Code-Zero/Support/Assets.xcassets/icChallengeOpenBottle.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icChallengeOpenBottle.imageset/icChallengeOpenBottle.png
  Code-Zero/Support/Assets.xcassets/icChallengeOpenBottle.imageset/icChallengeOpenBottle@2x.png
  Code-Zero/Support/Assets.xcassets/icChallengeOpenBottle.imageset/icChallengeOpenBottle@3x.png
  Code-Zero/Support/Assets.xcassets/icChallengeOpenDots.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icChallengeOpenDots.imageset/icChallengeOpenDots.png
  Code-Zero/Support/Assets.xcassets/icChallengeOpenDots.imageset/icChallengeOpenDots@2x.png
  Code-Zero/Support/Assets.xcassets/icChallengeOpenDots.imageset/icChallengeOpenDots@3x.png
  Code-Zero/Support/Assets.xcassets/icNavBottle.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icNavBottle.imageset/icNavBottle.png
  Code-Zero/Support/Assets.xcassets/icNavBottle.imageset/icNavBottle@2x.png
  Code-Zero/Support/Assets.xcassets/icNavBottle.imageset/icNavBottle@3x.png
Labels: feature, 주혁🥛, layout💄

#32 팔로우/보틀월드/둘러보기,팔로우,팔로워 有
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Extension/UILabel+Extension.swift
  Code-Zero/Global/Extension/UITableView+Extension.swift
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.swift
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.xib
  Code-Zero/Screen/BottleWorld/Cell/UserListCell.swift
  Code-Zero/Screen/BottleWorld/Cell/UserListCell.xib
  Code-Zero/Screen/BottleWorld/VC/BottleWorldVC.swift
  Code-Zero/Screen/BottleWorld/View/UserListView.swift
  Code-Zero/Screen/BottleWorld/View/UserListView.xib
  Code-Zero/Screen/Calendar/VC/ChallengeTitleView.swift
  Code-Zero/Support/Lottie/loading.json
Labels: 민희🍪, layout💄

#34 온보딩/시작하기
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Extension/UILabel+Extension.swift
  Code-Zero/Global/Extension/UIWindow+Extension.swift
  Code-Zero/Screen/Challenge/Storyboards/Challenge.storyboard
  Code-Zero/Screen/Home/Base.lproj/Main.storyboard
  Code-Zero/Screen/Home/Storyboard/Base.lproj/Home.storyboard
  Code-Zero/Screen/Home/VC/HomeVC.swift
  Code-Zero/Screen/Onboarding/Storyboard/Onboarding.storyboard
  Code-Zero/Screen/Onboarding/VC/OnboardingStepOneVC.swift
  Code-Zero/Support/Assets.xcassets/imgApple.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/imgApple.imageset/imgApple.png
  Code-Zero/Support/Assets.xcassets/imgApple.imageset/imgApple@2x.png
  Code-Zero/Support/Assets.xcassets/imgApple.imageset/imgApple@3x.png
  Code-Zero/Support/Assets.xcassets/imgKakao.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/imgKakao.imageset/imgKakao.png
  Code-Zero/Support/Assets.xcassets/imgKakao.imageset/imgKakao@2x.png
  Code-Zero/Support/Assets.xcassets/imgKakao.imageset/imgKakao@3x.png
  Code-Zero/Support/Info.plist
Labels: feature, 주혁🥛, layout💄
