Repository 0-Crew/i-zero-s, pull requests merged in 2022-02, with the labels that each got.

#38 설정/회원가입
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Screen/SignUp/Storyboard/SignUp.storyboard
  Code-Zero/Screen/SignUp/VC/NickSettingVC.swift
  Code-Zero/Screen/SignUp/VC/SignInVC.swift
  Code-Zero/Support/Assets.xcassets/icArrowLeftDart.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icArrowLeftDart.imageset/icArrowLeftDart.png
  Code-Zero/Support/Assets.xcassets/icArrowLeftDart.imageset/icArrowLeftDart@2x.png
  Code-Zero/Support/Assets.xcassets/icArrowLeftDart.imageset/icArrowLeftDart@3x.png
  Code-Zero/Support/Info.plist
Labels: feature, 민희🍪, layout💄

#44 온보딩4
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Extension/UILabel+Extension.swift
  Code-Zero/Global/Extension/UIViewController+Extension.swift
  Code-Zero/Global/Model/Constants.swift
  Code-Zero/Screen/Onboarding/Storyboard/Onboarding.storyboard
  Code-Zero/Screen/Onboarding/VC/OnboardingStepFourVC.swift
  Code-Zero/Support/Lottie/onboarding.json
Labels: feature, 주혁🥛, layout💄

#48 챌린지/종료
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Model/Constants.swift
  Code-Zero/Screen/Challenge/Storyboards/Challenge.storyboard
  Code-Zero/Screen/ChallengeFinal/ChallengeFinalVC.swift
  Code-Zero/Screen/ChallengeFinal/FinalChallengeView.swift
  Code-Zero/Screen/ChallengeFinal/Storyboards/ChallengeFinal.storyboard
  Code-Zero/Screen/ChallengeFinal/Storyboards/FinalChallengeView.xib
  Code-Zero/Support/Assets.xcassets/icChallengeFinalPopup.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icChallengeFinalPopup.imageset/icChallengeFinalPopup.png
  Code-Zero/Support/Assets.xcassets/icChallengeFinalPopup.imageset/icChallengeFinalPopup@2x.png
  Code-Zero/Support/Assets.xcassets/icChallengeFinalPopup.imageset/icChallengeFinalPopup@3x.png
  Code-Zero/Support/Assets.xcassets/icMiniWaterNoneChallengeFinal.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icMiniWaterNoneChallengeFinal.imageset/icMiniWaterNoneChallengeFinal.png
  Code-Zero/Support/Assets.xcassets/icMiniWaterNoneChallengeFinal.imageset/icMiniWaterNoneChallengeFinal@2x.png
  Code-Zero/Support/Assets.xcassets/icMiniWaterNoneChallengeFinal.imageset/icMiniWaterNoneChallengeFinal@3x.png
  Code-Zero/Support/Info.plist
Labels: feature, 주혁🥛, layout💄

#46 설정/계정
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Screen/Account/Storyboard/Account.storyboard
  Code-Zero/Screen/Account/VC/AccountDeleteVC.swift
  Code-Zero/Screen/Account/VC/AccountNickVC.swift
  Code-Zero/Screen/Account/VC/AccountPrivacyVC.swift
  Code-Zero/Screen/Account/VC/AccountSettingVC.swift
  Code-Zero/Screen/Home/Storyboard/Base.lproj/Home.storyboard
  Code-Zero/Screen/Setting/Storyboard/Setting.storyboard
  Code-Zero/Screen/Setting/Storyboard/UserView.xib
  Code-Zero/Screen/Setting/VC/SettingVC.swift
  Code-Zero/Screen/Setting/VC/UserView.swift
  Code-Zero/Support/Assets.xcassets/icArrowLeftDark.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icArrowLeftDark.imageset/icArrowLeftDark.png
  Code-Zero/Support/Assets.xcassets/icArrowLeftDark.imageset/icArrowLeftDark@2x.png
  Code-Zero/Support/Assets.xcassets/icArrowLeftDark.imageset/icArrowLeftDark@3x.png
  Code-Zero/Support/Assets.xcassets/icCheckOrange.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icCheckOrange.imageset/icCheckOrange.png
  Code-Zero/Support/Assets.xcassets/icCheckOrange.imageset/icCheckOrange@2x.png
  Code-Zero/Support/Assets.xcassets/icCheckOrange.imageset/icCheckOrange@3x.png
  Code-Zero/Support/Assets.xcassets/icEditOrange.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/icEditOrange.imageset/icEditOrange.png
  Code-Zero/Support/Assets.xcassets/icEditOrange.imageset/icEditOrange@2x.png
  Code-Zero/Support/Assets.xcassets/icEditOrange.imageset/icEditOrange@3x.png
Labels: feature, 민희🍪, layout💄

#55 챌린지 추가시 미리보기 불러오기 API 연결
  .swiftlint.yml
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Model/Convenience.swift
  Code-Zero/Global/Model/UserChallenge.swift
  Code-Zero/Global/Service/APITarget.swift
  Code-Zero/Global/Service/ChallengeOpenPreviewService.swift
  Code-Zero/Global/View/Indicator.swift
  Code-Zero/Screen/ChallengeOpen/VC/ChallengeOpenVC.swift
  Code-Zero/Screen/ChallengeOpen/View/ChallengeOpenFirstStepView.swift
  Code-Zero/Screen/ChallengeOpen/View/ChallengeOpenSecondStepView.swift
  Code-Zero/Support/Info.plist
Labels: feature, network, 주혁🥛

#57 애플 로그인 기능 추가 및 로그인/회원가입 네트워크 연결
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Code-Zero.entitlements
  Code-Zero/Global/Model/UserLoginData.swift
  Code-Zero/Global/Service/APITarget.swift
  Code-Zero/Global/Service/UserLoginService.swift
  Code-Zero/Screen/BottleWorld/StoryBoard/BottleWorld.storyboard
  Code-Zero/Screen/SignUp/Storyboard/SignUp.storyboard
  Code-Zero/Screen/SignUp/VC/SignInVC.swift
  Code-Zero/Support/Assets.xcassets/Logo - SIWA - Logo-only - Black.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/Logo - SIWA - Logo-only - Black.imageset/Logo - SIWA - Logo-only - Black@1x.png
  Code-Zero/Support/Assets.xcassets/Logo - SIWA - Logo-only - Black.imageset/Logo - SIWA - Logo-only - Black@2x.png
  Code-Zero/Support/Assets.xcassets/Logo - SIWA - Logo-only - Black.imageset/Logo - SIWA - Logo-only - Black@3x.png
  Code-Zero/Support/Assets.xcassets/logoAppleBlack.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/logoAppleBlack.imageset/Logo - SIWA - Logo-only - White@1x.png
  Code-Zero/Support/Assets.xcassets/logoAppleBlack.imageset/Logo - SIWA - Logo-only - White@2x.png
  Code-Zero/Support/Assets.xcassets/logoAppleBlack.imageset/Logo - SIWA - Logo-only - White@3x.png
  Code-Zero/Support/Delegate/SceneDelegate.swift
  Code-Zero/Support/Info.plist
Labels: feature, network, 민희🍪

#59 보틀월드 둘러보기 네트워크
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Extension/String+Extension.swift
  Code-Zero/Global/Model/BottleWorldUser.swift
  Code-Zero/Global/Model/UserChallenge.swift
  Code-Zero/Global/Service/APITarget.swift
  Code-Zero/Global/Service/BottleWorldService.swift
  Code-Zero/Screen/BottleWorld/Cell/BottleWorldListCell.swift
  Code-Zero/Screen/BottleWorld/Cell/UserListCell.swift
  Code-Zero/Screen/BottleWorld/View/UserListView.swift
  Code-Zero/Support/Info.plist
Labels: style, feature, network, 민희🍪

#61 내 챌린지 추가하기 API 추가
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Service/APITarget.swift
  Code-Zero/Global/Service/ChallengeOpenPreviewService.swift
  Code-Zero/Global/Service/ChallengeOpenService.swift
  Code-Zero/Screen/ChallengeOpen/VC/ChallengeOpenVC.swift
  Code-Zero/Screen/ChallengeOpen/View/ChallengeOpenFirstStepView.swift
Labels: feature, network, 주혁🥛
