Repository 0-Crew/i-zero-s, pull requests merged in 2022-08, with the labels that each got.

#108 상단내비/달력 - 현재 진행중인 챌린지 문제 수정
  Code-Zero/Screen/Calendar/VC/CalendarVC.swift
Labels: bug, feature, 민희🍪, QA

#110 회원가입/로그인 API 파라미터 추가
  Code-Zero/Global/Service/APITarget.swift
  Code-Zero/Global/Service/UserLoginService.swift
  Code-Zero/Screen/Home/VC/HomeVC.swift
  Code-Zero/Screen/Onboarding/VC/OnboardingStepFourVC.swift
  Code-Zero/Screen/SignUp/VC/SignInVC.swift
Labels: network, 민희🍪

#111 보틀 비우기 API 연결/화면연결
  Code-Zero.xcodeproj/project.pbxproj
  Code-Zero/Global/Model/Convenience.swift
  Code-Zero/Global/Model/UserChallenge.swift
  Code-Zero/Global/Service/APITarget.swift
  Code-Zero/Global/Service/MainChallengeService.swift
  Code-Zero/Screen/Challenge/VC/ChallengeVC+Network.swift
  Code-Zero/Screen/Challenge/VC/ChallengeVC.swift
  Code-Zero/Screen/ChallengeFinal/ChallengeFinalVC.swift
  Code-Zero/Screen/ChallengeFinal/FinalChallengeView.swift
  Code-Zero/Screen/ChallengeFinal/Storyboards/ChallengeFinal.storyboard
  Code-Zero/Screen/ChallengeFinal/Storyboards/FinalChallengeView.xib
  Code-Zero/Screen/ChallengeFinal/VC/CompletedChallengeFinalVC.swift
  Code-Zero/Screen/ChallengeFinal/VC/UncompletedChallengeFinalFixableVC.swift
  Code-Zero/Screen/ChallengeFinal/VC/UncompletedChallengeFinalVC.swift
  Code-Zero/Support/Assets.xcassets/imgFinish.imageset/Contents.json
  Code-Zero/Support/Assets.xcassets/imgFinish.imageset/imgFinish.png
  Code-Zero/Support/Assets.xcassets/imgFinish.imageset/imgFinish@2x.png
  Code-Zero/Support/Assets.xcassets/imgFinish.imageset/imgFinish@3x.png
Labels: feature, network, layout💄
